#! /usr/bin/python3.4


r_d = 500
c_l = 1*10e-4


for L0 in [520]:
    L1 = 1000 - L0
    W0 = 10
    W1 = 1
    R0 = 500*L0/W0
    C0 = (2*10e-6)*L0*W0
    R1 = 500*L1/W1
    C1 = (2*10e-6)*L1*W1
    d = r_d*(C0+C1+c_l) + R0*(C0/2+C1+c_l) + R1*(C1/2+c_l)
    print(L0, d)
